### ISSUE TITLE
TrafficSplit CRD schema should disallow negative weight

### ISSUE THREAD

**Issue by sjberman** [servicemeshinterface/smi-controller-sdk#20]
Per my understanding of how `weight` works, a negative value wouldn't make sense. To prevent user input error, `weight` should have a minimum value of 0.

This could be set in the OpenAPI schema like so:

```
weight:
    description: Weight defines the traffic split percentage
    type: integer
    minimum: 0 
```

Would this warrant a version bump to v1alpha5? Or could this be retroactively added to all previous versions?
